### ISSUE TITLE
Setting domain name for hosted portal

### ISSUE THREAD

**Issue by leafofcactus** [gbif/hp-eabcn#17]
Dear Matt,

We kindly request your assistance in setting up the DNS for this hosted portal, specifically as www.eabcn_portal.net.

Please excuse us for not having an IT department available to assist us.

Our node manager will handle responses regarding the hosted portal service and data processing agreements.

Thank you in advance for your assistance.

Best regards,
Jaesang

**Comment by MattBlissett** [comment]
Hi Jaesang,

Just closing this issue, as we have the portal at https://data.eabcn.net/

Thanks,
